### ISSUE TITLE
TransitionTo concats route name to URL

### ISSUE THREAD

**Issue by andrewPavlick** [villander/ember-engines-router-service#30]
In our application, we have a parent carousel component, depending on certain variables one of four children component containers will be used along with a series of product tile components within. When a product tile is clicked on the service router's `transitionTo(‘url’)` is invoked. 

![Screen Shot 2021-03-12 at 10 33 22 AM](https://user-images.githubusercontent.com/1900035/110963139-b80cbf00-831f-11eb-9102-bd796ad7bc5b.png)

Of these four children components, one exists in an ember engine & first passes through the ember-engine-router-service(_ERS_) when a click event is registered. In this instance, `Router_doTransition()` will eventually fail as the route name & URL have been merged together when passing through ERS, as shown below. ExternalRoutes configuration arrays for the app & engine both include the needed route names.

![Screen Shot 2021-03-12 at 10 33 48 AM](https://user-images.githubusercontent.com/1900035/110963466-176acf00-8320-11eb-8ef2-bd289385e751.png)

**Comment by villander** [comment]
Fixed by #39
